config/routes.rb
Nested::Application.routes.draw do
  resources :purchase_order_items

  resources :purchase_orders

  resources :vendors

  resources :companies

  resources :users

end

app/models/purchase_order_item.rb
class PurchaseOrderItem < ActiveRecord::Base
  belongs_to :purchase_order
end

app/controllers/purchase_order_items_controller.rb
class PurchaseOrderItemsController < ApplicationController
  # GET /purchase_order_items
  # GET /purchase_order_items.json
  def index
    @purchase_order_items = PurchaseOrderItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @purchase_order_items }
    end
  end

  # GET /purchase_order_items/1
  # GET /purchase_order_items/1.json
  def show
    @purchase_order_item = PurchaseOrderItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @purchase_order_item }
    end
  end

  # GET /purchase_order_items/new
  # GET /purchase_order_items/new.json
  def new
    @purchase_order_item = PurchaseOrderItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @purchase_order_item }
    end
  end

  # GET /purchase_order_items/1/edit
  def edit
    @purchase_order_item = PurchaseOrderItem.find(params[:id])
  end

  # POST /purchase_order_items
  # POST /purchase_order_items.json
  def create
    @purchase_order_item = PurchaseOrderItem.new(params[:purchase_order_item])

    respond_to do |format|
      if @purchase_order_item.save
        format.html { redirect_to @purchase_order_item, notice: 'Purchase order item was successfully created.' }
        format.json { render json: @purchase_order_item, status: :created, location: @purchase_order_item }
      else
        format.html { render action: "new" }
        format.json { render json: @purchase_order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /purchase_order_items/1
  # PUT /purchase_order_items/1.json
  def update
    @purchase_order_item = PurchaseOrderItem.find(params[:id])

    respond_to do |format|
      if @purchase_order_item.update_attributes(params[:purchase_order_item])
        format.html { redirect_to @purchase_order_item, notice: 'Purchase order item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @purchase_order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchase_order_items/1
  # DELETE /purchase_order_items/1.json
  def destroy
    @purchase_order_item = PurchaseOrderItem.find(params[:id])
    @purchase_order_item.destroy

    respond_to do |format|
      format.html { redirect_to purchase_order_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/purchase_order_items_helper.rb
module PurchaseOrderItemsHelper
end

app/views/purchase_order_items/_form.html.erb
<%= form_for(@purchase_order_item) do |f| %>
  <% if @purchase_order_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase_order_item.errors.count, "error") %> prohibited this purchase_order_item from being saved:</h2>

      <ul>
      <% @purchase_order_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/purchase_order_items/edit.html.erb
<h1>Editing purchase_order_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchase_order_item %> |
<%= link_to 'Back', purchase_order_items_path %>

app/views/purchase_order_items/index.html.erb
<h1>Listing purchase_order_items</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @purchase_order_items.each do |purchase_order_item| %>
  <tr>
    <td><%= link_to 'Show', purchase_order_item %></td>
    <td><%= link_to 'Edit', edit_purchase_order_item_path(purchase_order_item) %></td>
    <td><%= link_to 'Destroy', purchase_order_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Purchase order item', new_purchase_order_item_path %>

app/views/purchase_order_items/new.html.erb
<h1>New purchase_order_item</h1>

<%= render 'form' %>

<%= link_to 'Back', purchase_order_items_path %>

app/views/purchase_order_items/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_purchase_order_item_path(@purchase_order_item) %> |
<%= link_to 'Back', purchase_order_items_path %>